<?php

//Main Admin interface Things

function bit_admin_page() {
	//Creates admin page
}

function bit_admin_import_csv( $playid ) {
	//Imports the CSV into play
}

function bit_admin_show_playlines( $playid ) {
	//Shows all the play lines and related media
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ImportarContenidosMultimedia {
	private $importar_contenidos_multimedia_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'importar_contenidos_multimedia_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'importar_contenidos_multimedia_page_init' ) );
	}

	public function importar_contenidos_multimedia_add_plugin_page() {
		add_management_page(
			'Importar contenidos multimedia', // page_title
			'Importar contenidos multimedia', // menu_title
			'manage_options', // capability
			'importar-contenidos-multimedia', // menu_slug
			array( $this, 'importar_contenidos_multimedia_create_admin_page' ) // function
		);
	}

	public function importar_contenidos_multimedia_create_admin_page() {
		$this->importar_contenidos_multimedia_options = get_option( 'importar_contenidos_multimedia_option_name' ); ?>

		<div class="wrap">
			<h2>Importar contenidos multimedia</h2>
			<p>Importa contenido multimedia desde una carpeta predefinida</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'importar_contenidos_multimedia_option_group' );
					do_settings_sections( 'importar-contenidos-multimedia-admin' );
					//submit_button();
				?>
			</form>
		</div>
	<?php }

	public function importar_contenidos_multimedia_page_init() {
		register_setting(
			'importar_contenidos_multimedia_option_group', // option_group
			'importar_contenidos_multimedia_option_name', // option_name
			array( $this, 'importar_contenidos_multimedia_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'importar_contenidos_multimedia_setting_section', // id
			'Settings', // title
			array( $this, 'importar_contenidos_multimedia_section_info' ), // callback
			'importar-contenidos-multimedia-admin' // page
		);


		add_settings_field(
			'list_0', // id
			'Lista de medios en obras', // title
			array( $this, 'list_0_callback' ), // callback
			'importar-contenidos-multimedia-admin', // page
			'importar_contenidos_multimedia_setting_section' // section
		);
	}

	public function importar_contenidos_multimedia_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['generar_0'] ) ) {
			$sanitary_values['generar_0'] = sanitize_text_field( $input['generar_0'] );
		}

		return $sanitary_values;
	}

	public function importar_contenidos_multimedia_section_info() {
		
	}

	public function list_0_callback() {
		$args = array(
			'taxonomy' => 'obra',
			'hide_empty'	=> false
		);
		$obras = get_terms( $args );

		foreach($obras as $obra) {

			echo '<div class="obra-container" data-playid="' . $obra->term_id . '">';
			echo '<h2>' . $obra->name . '</h2>';
			$contenidos = bit_get_all_media_from_db($obra->term_id);

			echo 'allow_url_fopen = ', ini_get('allow_url_fopen');
			echo '<p>' . count($contenidos) .' materiales asociados a la obra</p>';

			if($contenidos):
				echo '<ul id="medialist">';
					foreach($contenidos as $contenido):
						echo '<li data-id="'. $contenido->mediaid .'" data-mediatype="' . $contenido->tipo_material . '">ID: ' . $contenido->mediaid . '</li>';
					endforeach;
				echo '</ul>';
			endif;

			echo '<div class="play-messages" data-play-id="' . $obra->term_id . '"></div>';

			echo '<button data-play-id="' . $obra->term_id . '" class="importar_contenidos">Importar contenidos desde carpeta</button>';
			echo '<hr>';
			echo '</div>';
		}

	}


}
if ( is_admin() )
	$importar_contenidos_multimedia = new ImportarContenidosMultimedia();

/* 
 * Retrieve this value with:
 * $importar_contenidos_multimedia_options = get_option( 'importar_contenidos_multimedia_option_name' ); // Array of All Options
 * $generar_0 = $importar_contenidos_multimedia_options['generar_0']; // Generar
 */
